name: Release
on:
  push:
    branches:
      - "**"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: geosysx/geostack:latest
      -
        name: Inspect
        run:  docker image inspect geosysx/geostack:latest
      -
        name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      -
        name: Install dependencies
        run:  npm install @semantic-release/exec -D
      -
        name: Run semantic-release
        run:  npx semantic-release
        env:  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
